In [17]:
import numpy as np
import numpy.random as rnd
import numpy.linalg
import matplotlib.pyplot as plt
from numpy import linalg as LA
from numpy.random import normal
import scipy
from scipy.spatial.transform import Rotation as R

Nx=2
Ny=2
dim=[Nx,Ny,3,2]

config = 2*np.random.rand(dim[0],dim[1],dim[2],3) - 1.0
#norms = np.linalg.norm(config, axis=3, keepdims=True)    # shape (...,1)
#selfconfig = config / norms
print(selfconfig)


[[[[ 0.96365802 -0.0561396  -0.26117344]
   [-0.62843816 -0.31567047  0.71092731]
   [ 0.63640355  0.66543603 -0.39010949]]

  [[-0.99152762 -0.01216463  0.12932517]
   [-0.6956072  -0.37379271 -0.61352232]
   [ 0.29769081  0.29015092 -0.9095013 ]]]


 [[[ 0.59419237 -0.38309714 -0.7072284 ]
   [ 0.72281917  0.69011887  0.03561455]
   [-0.50257173  0.40489269  0.76386096]]

  [[ 0.90484669  0.39559873 -0.15733439]
   [-0.4134047   0.89729515  0.15478361]
   [ 0.9845062   0.16225501 -0.06648952]]]]
